name: nirupon_pos
description: "POS Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get: ^4.6.6
  path_provider: ^2.1.1
  intl: any
  android_alarm_manager_plus: ^3.0.4
  google_fonts: ^6.1.0
  cart_stepper: ^4.3.0
  font_awesome_flutter: any
  shimmer: ^3.0.0
  dropdown_button2: ^2.3.9
  vertical_scrollable_tabview: ^0.1.1
  path: ^1.8.3
  page_transition: ^2.1.0
  badges: ^3.1.2
  pie_chart: ^5.4.0
  calendar_timeline: ^1.1.2
  d_chart: ^2.6.9
  flutter_slidable: ^3.1.0
  logger: ^2.2.0  
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  awesome_notifications: ^0.8.2
  flutter_svg: ^2.0.10+1
  otp_text_field: ^1.1.3
  image_picker: ^1.0.7
  bcrypt: ^1.1.3
  camera: ^0.10.5+9
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  permission_handler: ^11.3.1
  sqflite: ^2.3.3
  device_info_plus: ^10.1.0
  fluttertoast: ^8.2.5
  flutter_typeahead: ^5.2.0
  

dev_dependencies:
  flutter_lints: ^3.0.2
  pub_semver: ^2.1.4
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  rename_app: ^1.3.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 700
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
    - family: Noto Sans Bengali
      fonts:
        - asset: assets/fonts/noto_sans_bengali/NotoSansBengali-Thin.ttf
          weight: 100
        - asset: assets/fonts/noto_sans_bengali/NotoSansBengali-Regular.ttf
          weight: 400
        - asset: assets/fonts/noto_sans_bengali/NotoSansBengali-SemiBold.ttf
          weight: 600